/* =========================================================
   Породы для поля «Порода» в квизе: [русское название, English name]
   Порядок: метис/беспородная → популярные (сначала небольшие) → остальные по алфавиту.
   Популярность — по рейтингу РКФ за 2025 год; если породы нет в списке,
   посетитель может вписать свою.
   ========================================================= */
(function () {
  const dogPopular = [
    ["Метис", "Mixed breed"],
    // популярные небольшие
    ["Немецкий шпиц", "German Spitz"],
    ["Померанский шпиц", "Pomeranian"],
    ["Чихуахуа", "Chihuahua"],
    ["Вельш-корги пемброк", "Pembroke Welsh Corgi"],
    ["Пудель той", "Toy Poodle"],
    ["Пудель миниатюрный", "Miniature Poodle"],
    ["Кавалер-кинг-чарльз-спаниель", "Cavalier King Charles Spaniel"],
    ["Йоркширский терьер", "Yorkshire Terrier"],
    ["Джек-рассел-терьер", "Jack Russell Terrier"],
    ["Мальтипу", "Maltipoo"],
    ["Французский бульдог", "French Bulldog"],
    ["Русский той-терьер", "Russian Toy"],
    ["Такса", "Dachshund"],
    ["Такса миниатюрная", "Miniature Dachshund"],
    ["Ши-тцу", "Shih Tzu"],
    ["Мопс", "Pug"],
    ["Мальтезе (мальтийская болонка)", "Maltese"],
    ["Бишон фризе", "Bichon Frise"],
    ["Цвергшнауцер", "Miniature Schnauzer"],
    ["Сиба-ину", "Shiba Inu"],
    ["Бигль", "Beagle"],
    ["Вельш-корги кардиган", "Cardigan Welsh Corgi"],
    ["Пекинес", "Pekingese"],
    ["Папийон", "Papillon"],
    ["Бивер-йоркширский терьер", "Biewer Terrier"],
    ["Вест-хайленд-уайт-терьер", "West Highland White Terrier"],
    ["Китайская хохлатая", "Chinese Crested"],
    ["Шелти", "Shetland Sheepdog"],
    ["Бостон-терьер", "Boston Terrier"],
    ["Пти-брабансон", "Petit Brabancon"],
    ["Гриффон брюссельский", "Brussels Griffon"],
    ["Японский хин", "Japanese Chin"],
    ["Лхаса апсо", "Lhasa Apso"],
    ["Цвергпинчер", "Miniature Pinscher"],
    ["Английский бульдог", "English Bulldog"],
    ["Кокер-спаниель английский", "English Cocker Spaniel"],
    ["Кокер-спаниель американский", "American Cocker Spaniel"],
    // популярные средние и крупные
    ["Немецкая овчарка", "German Shepherd"],
    ["Лабрадор-ретривер", "Labrador Retriever"],
    ["Золотистый ретривер", "Golden Retriever"],
    ["Сибирский хаски", "Siberian Husky"],
    ["Среднеазиатская овчарка (алабай)", "Central Asian Shepherd (Alabai)"],
    ["Кавказская овчарка", "Caucasian Shepherd"],
    ["Самоедская собака", "Samoyed"],
    ["Австралийская овчарка (аусси)", "Australian Shepherd"],
    ["Бордер-колли", "Border Collie"],
    ["Доберман", "Doberman"],
    ["Ротвейлер", "Rottweiler"],
    ["Кане-корсо", "Cane Corso"],
    ["Американский стаффордширский терьер", "American Staffordshire Terrier"],
    ["Стаффордширский бультерьер", "Staffordshire Bull Terrier"],
    ["Бультерьер", "Bull Terrier"],
    ["Акита-ину", "Akita Inu"],
    ["Аляскинский маламут", "Alaskan Malamute"],
    ["Боксёр", "Boxer"],
    ["Бернский зенненхунд", "Bernese Mountain Dog"],
    ["Бельгийская овчарка малинуа", "Belgian Malinois"],
    ["Веймаранер", "Weimaraner"],
    ["Далматин", "Dalmatian"],
    ["Шарпей", "Shar Pei"],
    ["Чау-чау", "Chow Chow"],
    ["Пудель большой (королевский)", "Standard Poodle"],
    ["Ризеншнауцер", "Giant Schnauzer"],
    ["Миттельшнауцер", "Standard Schnauzer"],
    ["Курцхаар", "German Shorthaired Pointer"],
    ["Русский охотничий спаниель", "Russian Spaniel"],
    ["Западносибирская лайка", "West Siberian Laika"],
    ["Немецкий дог", "Great Dane"],
    ["Ньюфаундленд", "Newfoundland"],
    ["Сенбернар", "St. Bernard"],
    ["Ирландский сеттер", "Irish Setter"],
  ];

  // остальные породы — по алфавиту
  const dogRest = [
    ["Аффенпинчер", "Affenpinscher"], ["Афганская борзая", "Afghan Hound"], ["Айрдейл-терьер", "Airedale Terrier"],
    ["Акбаш", "Akbash"], ["Американский акита", "American Akita"], ["Американский бульдог", "American Bulldog"],
    ["Американский булли", "American Bully"], ["Американский питбультерьер", "American Pit Bull Terrier"],
    ["Американский эскимосский шпиц", "American Eskimo Dog"], ["Американский голый терьер", "American Hairless Terrier"],
    ["Американский водяной спаниель", "American Water Spaniel"], ["Анатолийская овчарка (кангал)", "Anatolian Shepherd (Kangal)"],
    ["Английский пойнтер", "English Pointer"], ["Английский сеттер", "English Setter"], ["Английский спрингер-спаниель", "English Springer Spaniel"],
    ["Английский той-терьер", "English Toy Terrier"], ["Английский мастиф", "English Mastiff"], ["Английская борзая (грейхаунд)", "Greyhound"],
    ["Аргентинский дог", "Dogo Argentino"], ["Австралийский келпи", "Australian Kelpie"], ["Австралийский пастуший пёс", "Australian Cattle Dog"],
    ["Австралийский терьер", "Australian Terrier"], ["Австралийский шелковистый терьер", "Australian Silky Terrier"],
    ["Азавак", "Azawakh"], ["Барбет", "Barbet"], ["Басенджи", "Basenji"], ["Бассет-хаунд", "Basset Hound"],
    ["Бедлингтон-терьер", "Bedlington Terrier"], ["Бельгийская овчарка грюнендаль", "Belgian Groenendael"],
    ["Бельгийская овчарка лакенуа", "Belgian Laekenois"], ["Бельгийская овчарка тервюрен", "Belgian Tervuren"],
    ["Бергамская овчарка", "Bergamasco Shepherd"], ["Бладхаунд", "Bloodhound"], ["Бобтейл (староанглийская овчарка)", "Old English Sheepdog"],
    ["Болонка болоньез", "Bolognese"], ["Бордоский дог", "Dogue de Bordeaux"], ["Бордер-терьер", "Border Terrier"],
    ["Борзая русская псовая", "Russian Borzoi"], ["Бородатая колли", "Bearded Collie"], ["Босерон", "Beauceron"],
    ["Бриар", "Briard"], ["Бретонский эпаньоль", "Brittany"], ["Бульмастиф", "Bullmastiff"], ["Бурбуль", "Boerboel"],
    ["Валлийский терьер", "Welsh Terrier"], ["Венгерская выжла", "Hungarian Vizsla"], ["Венгерский кувас", "Kuvasz"],
    ["Венгерский пули", "Puli"], ["Венгерский муди", "Mudi"], ["Восточноевропейская овчарка", "East European Shepherd"],
    ["Восточносибирская лайка", "East Siberian Laika"], ["Гаванский бишон", "Havanese"], ["Грейхаунд итальянский (левретка)", "Italian Greyhound"],
    ["Гладкошёрстный фокстерьер", "Smooth Fox Terrier"], ["Жесткошёрстный фокстерьер", "Wire Fox Terrier"], ["Голден-дудль", "Goldendoodle"],
    ["Голландская овчарка", "Dutch Shepherd"], ["Грузинская овчарка (нагази)", "Georgian Shepherd (Nagazi)"], ["Гончая русская", "Russian Hound"],
    ["Гончая эстонская", "Estonian Hound"], ["Денди-динмонт-терьер", "Dandie Dinmont Terrier"], ["Дратхаар", "German Wirehaired Pointer"],
    ["Дирхаунд", "Scottish Deerhound"], ["Евразиер", "Eurasier"], ["Ирландский волкодав", "Irish Wolfhound"],
    ["Ирландский мягкошёрстный пшеничный терьер", "Soft-Coated Wheaten Terrier"], ["Ирландский терьер", "Irish Terrier"],
    ["Ирландский водяной спаниель", "Irish Water Spaniel"], ["Исландская собака", "Icelandic Sheepdog"], ["Испанский мастиф", "Spanish Mastiff"],
    ["Испанская водяная собака", "Spanish Water Dog"], ["Итальянский спиноне", "Spinone Italiano"], 
    ["Кай-кен", "Kai Ken"], ["Каракачанская собака", "Karakachan"], ["Карельская медвежья собака", "Karelian Bear Dog"],
    ["Керн-терьер", "Cairn Terrier"], ["Керри-блю-терьер", "Kerry Blue Terrier"], ["Кишу", "Kishu Ken"], ["Кламбер-спаниель", "Clumber Spaniel"],
    ["Колли длинношёрстная", "Rough Collie"], ["Колли короткошёрстная", "Smooth Collie"], ["Комондор", "Komondor"],
    ["Континентальный бульдог", "Continental Bulldog"], ["Кромфорлендер", "Kromfohrlander"], ["Ксолоитцкуинтли (мексиканская голая)", "Xoloitzcuintli"],
    ["Курчавошёрстный ретривер", "Curly-Coated Retriever"], ["Лаготто-романьоло", "Lagotto Romagnolo"], ["Лабрадудль", "Labradoodle"],
    ["Ландсир", "Landseer"], ["Леонбергер", "Leonberger"], ["Левхен (маленькая львиная собачка)", "Lowchen"], ["Лейкленд-терьер", "Lakeland Terrier"],
    ["Манчестер-терьер", "Manchester Terrier"], ["Мастино наполетано", "Neapolitan Mastiff"], ["Мареммо-абруццкая овчарка", "Maremma Sheepdog"],
    ["Московская сторожевая", "Moscow Watchdog"], ["Немецкий вахтельхунд", "German Spaniel"],
    ["Немецкий ягдтерьер", "German Hunting Terrier"], ["Норвич-терьер", "Norwich Terrier"], ["Норфолк-терьер", "Norfolk Terrier"],
    ["Новошотландский ретривер", "Nova Scotia Duck Tolling Retriever"], ["Норвежский бухунд", "Norwegian Buhund"], ["Норвежский элкхаунд", "Norwegian Elkhound"],
    ["Оттерхаунд", "Otterhound"], ["Парсон-рассел-терьер", "Parson Russell Terrier"], ["Перуанская голая собака", "Peruvian Hairless Dog"],
    ["Пиренейская горная собака", "Great Pyrenees"], ["Пиренейская овчарка", "Pyrenean Shepherd"], ["Плотт-хаунд", "Plott Hound"],
    ["Португальская водяная собака", "Portuguese Water Dog"], ["Прямошёрстный ретривер", "Flat-Coated Retriever"], ["Польская низинная овчарка", "Polish Lowland Sheepdog"],
    ["Родезийский риджбек", "Rhodesian Ridgeback"], ["Русский чёрный терьер", "Black Russian Terrier"], ["Русская цветная болонка", "Russian Tsvetnaya Bolonka"],
    ["Русско-европейская лайка", "Russo-European Laika"], ["Салюки", "Saluki"], ["Сеттер гордон", "Gordon Setter"],
    ["Силихем-терьер", "Sealyham Terrier"], ["Скай-терьер", "Skye Terrier"], ["Скотч-терьер (шотландский терьер)", "Scottish Terrier"],
    ["Слюги", "Sloughi"], ["Стабихаун", "Stabyhoun"], ["Суссекс-спаниель", "Sussex Spaniel"],
    ["Тайский риджбек", "Thai Ridgeback"], ["Тибетский мастиф", "Tibetan Mastiff"], ["Тибетский спаниель", "Tibetan Spaniel"],
    ["Тибетский терьер", "Tibetan Terrier"], ["Тоса-ину", "Tosa Inu"], ["Уиппет", "Whippet"], ["Фараонова собака", "Pharaoh Hound"],
    ["Финский лаппхунд", "Finnish Lapphund"], ["Финский шпиц", "Finnish Spitz"], ["Филд-спаниель", "Field Spaniel"],
    ["Фила бразилейро", "Fila Brasileiro"], ["Хоккайдо", "Hokkaido"], ["Ховаварт", "Hovawart"], ["Хорватская овчарка", "Croatian Sheepdog"],
    ["Чесапик-бей-ретривер", "Chesapeake Bay Retriever"], ["Чехословацкая волчья собака", "Czechoslovakian Wolfdog"],
    ["Чешский терьер", "Cesky Terrier"], ["Шапендуа", "Dutch Sheepdog (Schapendoes)"], ["Швейцарская белая овчарка", "White Swiss Shepherd"],
    ["Шипперке", "Schipperke"], ["Энтлебухер зенненхунд", "Entlebucher Mountain Dog"],
    ["Аппенцеллер зенненхунд", "Appenzeller Sennenhund"], ["Большой швейцарский зенненхунд", "Greater Swiss Mountain Dog"],
    ["Южнорусская овчарка", "South Russian Ovcharka"], ["Японский шпиц", "Japanese Spitz"],
    ["Ягдтерьер", "Jagdterrier"], ["Ямтхунд", "Jamthund"], ["Кавапу", "Cavapoo"], ["Помски", "Pomsky"], ["Шиппу", "Shih-Poo"],
    
  ];

  const catPopular = [
    ["Беспородная", "Mixed breed"],
    ["Британская короткошёрстная", "British Shorthair"],
    ["Шотландская вислоухая", "Scottish Fold"],
    ["Шотландская прямоухая", "Scottish Straight"],
    ["Мейн-кун", "Maine Coon"],
    ["Сфинкс канадский", "Canadian Sphynx"],
    ["Донской сфинкс", "Donskoy"],
    ["Бенгальская", "Bengal"],
    ["Сиамская", "Siamese"],
    ["Персидская", "Persian"],
    ["Невская маскарадная", "Neva Masquerade"],
    ["Сибирская", "Siberian"],
    ["Рэгдолл", "Ragdoll"],
    ["Русская голубая", "Russian Blue"],
    ["Абиссинская", "Abyssinian"],
    ["Экзотическая короткошёрстная", "Exotic Shorthair"],
    ["Британская длинношёрстная", "British Longhair"],
    ["Ориентальная", "Oriental"],
    ["Тайская", "Thai"],
    ["Норвежская лесная", "Norwegian Forest Cat"],
  ];
  const catRest = [
    ["Американская короткошёрстная", "American Shorthair"], ["Американский керл", "American Curl"], ["Американский бобтейл", "American Bobtail"],
    ["Балинезийская", "Balinese"], ["Бирманская (священная бирма)", "Birman"], ["Бомбейская", "Bombay"], ["Бурманская", "Burmese"],
    ["Гималайская", "Himalayan"], ["Девон-рекс", "Devon Rex"], ["Египетская мау", "Egyptian Mau"], ["Корниш-рекс", "Cornish Rex"],
    ["Курильский бобтейл", "Kurilian Bobtail"], ["Лаперм", "LaPerm"], ["Ликой", "Lykoi"], ["Манчкин", "Munchkin"], ["Мэнкс", "Manx"],
    ["Нибелунг", "Nebelung"], ["Оцикет", "Ocicat"], ["Петерболд", "Peterbald"], ["Рагамаффин", "Ragamuffin"], ["Саванна", "Savannah"],
    ["Селкирк-рекс", "Selkirk Rex"], ["Сингапурская", "Singapura"], ["Сноу-шу", "Snowshoe"], ["Сомали", "Somali"], ["Тойгер", "Toyger"],
    ["Тонкинская", "Tonkinese"], ["Турецкая ангора", "Turkish Angora"], ["Турецкий ван", "Turkish Van"], ["Украинский левкой", "Ukrainian Levkoy"],
    ["Хайленд-фолд", "Highland Fold"], ["Чаузи", "Chausie"], ["Шартрез", "Chartreux"], ["Японский бобтейл", "Japanese Bobtail"],
    ["Йорская шоколадная", "York Chocolate"], ["Корат", "Korat"], ["Европейская короткошёрстная", "European Shorthair"],
    ["Меконгский бобтейл", "Mekong Bobtail"], ["Колорпойнт", "Colorpoint Shorthair"], ["Минскин", "Minskin"], ["Бамбино", "Bambino"],
  ];

  const sortRu = (a, b) => a[0].localeCompare(b[0], "ru");
  const uniq = (list) => {
    const seen = new Set();
    return list.filter(([ru]) => (seen.has(ru) ? false : seen.add(ru)));
  };

  window.BREEDS = {
    dog: uniq(dogPopular.concat(dogRest.slice().sort(sortRu))),
    cat: uniq(catPopular.concat(catRest.slice().sort(sortRu))),
  };
})();
